### ISSUE TITLE
Rename primary branch from master to main

### ISSUE THREAD

**Issue by linux-lukas** [TheMorpheus407/Tutorials#8]
# A. Problem / Aim

About two years ago, GitHub decided to move to Main due to the reference of Master and Slave Branchs to slavery in the Primary branch in GitHub projects. This move goes some way to reducing this real stigma, which I personally think is a good thing. The "problem" here is that this repo was created before this decision and therefore still has "master" as a primary branch. 

The aim would be to reduce this stigma for the sake of inclusion.

Compare https://www.bbc.com/news/technology-53050955 and https://t3n.de/news/wegen-bezug-sklaverei-github-1291113/

# B. Solution 

Rename the main branch from master to main.

# C. Alternatives 
None. 

# D. Jurisdiction 

- Owner or employee with sufficient rights (@TheMorpheus407, @vonrein, @Simonwep)

# E. Notes

I would think that this step would also make sense in the remaining repositories of the user @TheMorpheus407.

**Comment by HalloWelt42** [comment]
Those who smell racism everywhere should have their mental health checked.

**Comment by simonwep** [comment]
@Lukas2112 Why am I mentioned?

**Comment by linux-lukas** [comment]
You are one of three Repository Contributors.😅

**Comment by simonwep** [comment]
Gotchya, hey man - to be brutally honest. For me it's all about consistency, and I get the reason why GitHub changed it's default branch name for repositories to main, but in the end I really don't care if it's main or master or whatever. And, to speak from my point of view, since I currently still (most of the time) initialize my repos using git and git is still using `master` as it's default branch (for consistency) I'll go with this and won't take any initiative renaming the main/master branch from this or any of my >70 repos. (I also never thought about the term `master` going back to slavery, maybe I'm the wrong generation for this)

Also, only _owners_ can make changes to the settings, not contributors. So I'm the wrong guy for this job.

**Comment by TheMorpheus407** [comment]
done
